services:
  - type: web
    name: itanery-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --max-requests 1000 --preload"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
